### ISSUE TITLE
Handle texts in project

### ISSUE THREAD

**Issue by Joozty** [oacore/search#9]
In the dashboard we use separate text module where we store almost all text messages. It should help to manage all text in one place and even non dev people can easily change it.  It was the best solution we have had sofar. There are some downsides of it. Like for example it's harder to setup and you need to manually import newly created file and so on. 

I would like to treat this task as a discussion if we want to have the same text approach here or we want to try something different.  I know @viktor-yakubiv was exploring the Google Docs alternative which seemed promising. So feel free to comment with any ideas.

For the time being we can stick with text in code.

**Comment by viktor-yakubiv** [comment]
Google Docs idea is different, it's needed for the managers to smooth their life in editing and deployment. Editing things on GitHub gives too many options for the mistake and still involves developers for publishing changes.

We are not going to support internationalisation for our product. However, the reason for the `texts` module is enabling this from the project start. In the [dashboard](/oacore/dashboard) we did not do it well, the approach was too complicated. It was a dependency and adding into it, linking a new file in a few another ones and importing everything from there was too hard to let us put the text right into the code.

That should be solved somehow in an easy way for both the developers and the text editors. I do not see any option at the moment. However, since we don't support multiple languages now, we can put texts into the components like `texts.yml`. This is what I recommend at the moment.

At some point, we can collect all the `texts.yml` files in a separate module if it's needed.
